### ISSUE TITLE
Exception when using CTRL+D to exit REPL

### ISSUE THREAD

**Issue by jcubic** [blue-tiki/rheme#1]
I've got this exception when using CTRL+D
```
rheme> Traceback (most recent call last):
	3: from ./rheme.rb:879:in `<main>'
	2: from ./rheme.rb:727:in `repl'
	1: from ./rheme.rb:573:in `read_expr'
./rheme.rb:573:in `next': iteration reached an end (StopIteration)
```
I think that you can just ignore `StopIteration` exception.

**Comment by blue-tiki** [comment]
Thank you for the bug report.
CRTL+D should exit gracefully.
Will Fix.
